Agrotis/urls.py
from django.contrib import admin
from django.urls import path,include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls', namespace='blog'))
]+ static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

blog/urls.py
from django.urls import path
from .views import HomeView,PostView,AddPost

app_name = "blog"

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('post/<int:pk>', PostView.as_view(), name='post'),
    path('add', AddPost.as_view(), name='add')
]

blog/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.urls import reverse

# Create your models here.
class User(AbstractUser):
    pass

class Post(models.Model):
    title = models.CharField(max_length=100, null=False)
    image = models.ImageField(null=False, blank=False, upload_to='images/', default='null')
    content = models.TextField()
    date = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.title + " | " + str(self.author)

    def get_absolute_url(self):
        return reverse('blog:post', args=(str(self.id)))

blog/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView, CreateView
from .models import User, Post


# Create your views here.


class HomeView(ListView):
    model = Post
    template_name = 'home.html'


class PostView(DetailView):
    model = Post
    template_name = 'post.html'

class AddPost(CreateView):
    model = Post
    template_name = 'add.html'

    fields = '__all__'

templates/add.html
{% extends 'base.html' %}

{% block title %} New Post {% endblock %}

{% block content %}
    <form method="POST" enctype="multipart/form-data">
        <h1>Add Post</h1>
        {% csrf_token %}
        {{ form.as_p }}
        <button>Post</button>
    </form>
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
{% block content %}

{% endblock %}
</body>
</html>

templates/home.html
{% extends 'base.html' %}

{% block title %} Home Page {% endblock %}

{% block content %}
    <h2>Posts</h2>
    <button><a href="{% url 'blog:add' %}">Add post</a> </button>
    {% for post in object_list %}
        <li><a href="{% url 'blog:post' post.pk %}"> {{ post.title }}</a> - {{ post.author }} </br>
            {{ post.content }} </li>

    {% endfor %}

{% endblock %}

templates/post.html
{% extends 'base.html' %}

{% block title %} Post {% endblock %}

{% block content %}
    {{ post.title }}
    {{ post.content }}
    <img src="{{ post.image.url }}">
{% endblock %}